
name: CI

on:
  push:
    tags:
      - '*.*.*'


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: "get tag"
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          
      - name: Automatic Pre-Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Hier gibt's die neuste PDF"
          files: |
            CHANGELOG.md
